# ============================
#        Builder
# ============================
FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine:3.12 as builder

# Install build dependencies.
RUN apk update && \
    apk add --virtual build-dependencies \
            build-base \
            gcc \
            wget \
            git \
            autoconf \
            automake && \
    apk add --virtual jq-deps \
            bison \
            flex \
            libtool && \
    apk add bash

# Create directories for scripts, jq sources and output.
RUN mkdir /app /jq /out

COPY checkout.sh /app
COPY build-unix.sh /app

# Checkout jq commit.
ARG JQ_GIT_SHA
RUN /app/checkout.sh $JQ_GIT_SHA /jq

# Build libjq and jq binary, create checksum file in /out.
RUN /app/build-unix.sh /jq /out

# ============================
#        Final image
# ============================
FROM scratch
COPY --from=builder /out/ /
ENTRYPOINT ["/bin/jq"]
