# Script to build oniguruma and jq library in /out directory

FROM alpine:3.9
ADD . /libjq-go
WORKDIR /libjq-go

RUN /libjq-go/scripts/install-libjq-dependencies-alpine.sh && \
    /libjq-go/scripts/build-libjq-static.sh /libjq-go /out
